### ISSUE TITLE
Weird message causing `fromReqString` to fail

### ISSUE THREAD

**Issue by gurghet** [polynote/uzhttp#38]
Yesterday my server (yes, a production server) got stuck when processing a particular request that caused this:
```
╠══╦══╗
║  ║  ║
║  ║  ╠─An unchecked error was produced.
║  ║  ║ scala.MatchError: List(0) (of class scala.collection.immutable.$colon$colon)
║  ║  ║ 	at uzhttp.Request$NoBody$.fromReqString(Request.scala:97)
║  ║  ║ 	at uzhttp.server.Server$Connection.$anonfun$doRead$4(Server.scala:404)
║  ║  ║ 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:342)
║  ║  ║ 	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
║  ║  ║ 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
║  ║  ║ 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
║  ║  ║ 	at java.base/java.lang.Thread.run(Thread.java:834)
```
These are the last few request before failing:
```
[REQUEST] GET /gila/?c=admin 404 Not Found (4 ms to finish, 5 ms total) (closed)
[REQUEST] POST /actions/authenticate.php 404 Not Found (1 ms to finish, 1 ms total) (closed)
[REQUEST] GET / 200 OK (4 ms to finish, 29 ms total) (closed)
[REQUEST] GET /wp-login.php 404 Not Found (9 ms to finish, 9 ms total) (closed)
[REQUEST] POST /search.php?searchtype=5 404 Not Found (762423 ns to finish, 921797 ns total) (closed)
[REQUEST] POST /ws/v1/cluster/apps/new-application 404 Not Found (1 ms to finish, 1 ms total) (closed)
```
They have *nothing* to do with my website, except for the `/ 200 OK`. So I presume it's just part of some commonly used script to infect CMS websites.

**Comment by jeremyrsmith** [comment]
Thanks for the report @gurghet . I think #39 should fix it, and I'll release that now.

**Comment by jeremyrsmith** [comment]
0.2.7 is on its way to Maven Central.
